services:
  backend:
    build: ./backend
    container_name: fastfood_backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: fastfood_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin:
    build: ./admin
    container_name: fastfood_admin
    ports:
      - "3001:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: fastfood_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
